### ISSUE TITLE
Usage with a separate library and CRACO

### ISSUE THREAD

**Issue by AndrewJSchoen** [gzuidhof/wasmwrap#2]
Hi! Thanks for making this project, it seems like it might be just the thing I could use in my current project. My use case is that I have a fairly large rust-based WASM module that exports a struct with a couple methods, which take in a variety of serde-based JSValues. It looks something like this. Note, since this also exists as a separate thing with standard rust and python bindings, I only "export" the wasm-wrapped struct:

```
#[cfg(feature = "jsbindings")]
#[wasm_bindgen(js_name = MyStruct)]
pub struct JsMyStruct(MyStruct);

#[cfg(feature = "jsbindings")]
#[wasm_bindgen]
impl JsMyStruct {
    #[wasm_bindgen(constructor)]
    pub fn new(
        param1: String, 
        param2: &JsValue, 
        param3: &JsValue
    ) -> Self {
            /*
              Unwrap jsvalues
            */
            Self(MyStruct::new(uparam1, uparam2, uparam3))
    }
```

The wasm file that is generated sits at around 800 KB, and running wasmwrap on the output (let's call it `my_pkg_bg.wasm`) produces a file around 1.1 MB. I have been able to publish this to NPM. 

I am trying to use that library in another, react-based project that uses CRACO. Unfortunately, I am not much of an expert on bundling, and wasn't sure how I would go about loading the result of the wasmwrap file using CRACO. I see you have a rollup approach, but I can't really switch out of CRACO at this point. 

So I have 2 main questions:
1. Is `wasmwrap` a good approach for this use case? Would I expect that my module structure would work here?
2. Do you have any suggestions on how the bundling and usage would be handled on the react side?

Thanks so much!

**Comment by gzuidhof** [comment]
Hey, this sounds like the exact usecase for this small tool. The output of this tool is a plain Javascript (or typescript) file that you should be able to import like any other javascript file! No need for any special rules in your bundler (it doesn't have to know about wasmwrap at all).

You would import it like
```javascript
import {buffer} from "my_pkg_bg.wasm.wrap.js"

WebAssembly.compile(buffer)...
```

I hope this answers your question.

**Comment by AndrewJSchoen** [comment]
That is quite helpful to know. Forgive me a bit for my lack of familiarity with using WebAssembly in javascript at this point, so this may seem like an obvious answer. 

To start, I updated the NPM package.json to this:

```
{
  ...
  "files": [
    "my_pkg_lib_bg.wasm",
    "my_pkg_lib.js",
    "my_pkg_lib_bg.js",
    "my_pkg_lib.d.ts",
    "my_pkg_lib_bg.wasm.wrap.js",
    "my_pkg_lib_bg.wasm.wrap.ts"
  ],
  "module": "my_pkg_lib_bg.wasm.wrap.js",
  "types": "my_pkg_lib.d.ts",
  "sideEffects": false
}
```

Using that, I tried to load as such

```
import {buffer} from "@my_org/my_pkg";
...
async function getMyStruct() {
  const module = await WebAssembly.compile(buffer);
  const instance = await WebAssembly.instantiate(module,{});
  const myStructInst = instance.exports.MyStruct(param1, param2, param3);
  console.log(myStructInst)
}
getMyStruct()
```

However, on Chrome I get the following error: 

```
Unhandled Rejection (TypeError): WebAssembly.instantiate(): Import #0 module="./my_pkg_lib_bg.js" error: module is not an object or function
```
And in Safari I get:
```
Unhandled Promise Rejection: TypeError: import ./my_pkg_lib_bg.js:__wbindgen_json_parse must be an object
```

Again, I don't know if I am just doing something incorrect, or if there might be a bug somewhere. Any suggestions would be helpful. Thanks again so much!

**Comment by gzuidhof** [comment]
It looks fine, what does `console.log(buffer)` tell you?

**Comment by AndrewJSchoen** [comment]
I get back an ArrayBuffer object (picture attached)

![Screen Shot 2021-11-09 at 4 25 26 PM](https://user-images.githubusercontent.com/5341396/141015262-b890af32-3df0-4cdc-9bbf-0355ded88e15.png)

If there are any specific fields that would be helpful, let me know and I can provide what I can.

**Comment by gzuidhof** [comment]
I don't know what is going wrong here, maybe it's not wasmwrap or your bundling at all but something wrong with the WASM module itself? :/
